name: "Ask a question"
description: "Asking a question relating to ModernZ, its options or configuration"
labels: ["question"]
body:
- type: textarea
  attributes:
      label: "What is your question?"
      description: >
          Feel free to ask anything related to ModernZ, but we would appreciate it if you first read the available manuals linked in the main page.
  validations:
      required: true
