name: "Discussion"
description: "Discussing something related to ModernZ in detail. This could be about long term change or possible behavior adjustments. The uncertain areas."
labels: ["discussion"]
body:
- type: textarea
  attributes:
      label: "What would you like to discuss?"
      description: >
          Feel free to discuss anything. We only ask that you understand not everything can be done and to be open minded about the process.
  validations:
      required: true
